name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4

      - run: ./som.sh -cp core-lib/Smalltalk core-lib/TestSuite/TestHarness.som
      - run: ./som.sh -cp core-lib/Smalltalk:core-lib/TestSuite:core-lib/SomSom/src/compiler:core-lib/SomSom/src/vm:core-lib/SomSom/src/vmobjects:core-lib/SomSom/src/interpreter:core-lib/SomSom/src/primitives core-lib/SomSom/tests/SomSomTests.som

      - name: Integration Tests
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          export VM=./som.sh
          export CLASSPATH=Smalltalk
          export TEST_EXCEPTIONS=./integration-tests.yml
          pytest core-lib/IntegrationTests

      - run: npm ci
      - run: npm test
      - run: npm run lint
      - run: npm run browserify
